name: CI

on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string

env:
  APPLICATION_NAME: ${{ inputs.application_name }}

jobs:
  test_build_deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          name: buildoptima
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build With Maven
        run: |
          cd $APPLICATION_NAME
          mvn package -DskipTests